projects:
  api:
    schemaPath: "server/api/model.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "database/schema.graphql"
    extensions:
      prisma: database/prisma.yml
