---
language: node_js
node_js:
  - "0.10.36"

sudo: false

cache:
  directories:
    - node_modules

install:
  - "npm install"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

env:
  global:
    - CONTINOUS_INTEGRATION=true
