version: 2
jobs:
  build:
    working_directory: ~/este
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout

      - run: yarn

      - run: yarn test

      # TODO: Doesn't work, investigate why.
      # http://macklin.underdown.me/2017/07/27/deploy-to-now-from-circleci
